name: Activate Campaign

on:
  schedule:
    - cron: "5 11 * * *"  # Запуск каждый день в 12:00
  workflow_dispatch:

jobs:
  activate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run activation script
      run: python ActivateComp.py
