name: Deactivate Campaign

on:
  schedule:
    - cron: "50 5 * * *"   # Каждый день в 07:00-09:00
    - cron: "50 11 * * *"  # Каждый день в 11:00-15:00
    - cron: "50 20 * * *"  # Каждый день в 17:00-24:00
  workflow_dispatch:

jobs:
  deactivate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run deactivation script
      run: python DeactivateComp.py
